name: EarthSpirit
version: 1.0
main: com.example.earthspirit.EarthSpiritPlugin
api-version: 1.21
authors: [TraeAI]
softdepend: [Towny, BiomeGifts]
depend: [NexusCore]
commands:
  getbell:
    description: 获取灵契风铃
    permission: earthspirit.admin
  getwand:
    description: 获取风铃杖
    permission: earthspirit.admin
  esp:
    description: 地灵系统主命令
    aliases: [earthspirit]
    usage: /esp <subcommand>
